# Generated by Django 5.2.7 on 2025-10-11 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_departamento_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_trabajador', models.CharField(max_length=12)),
                ('nombre_trabajador', models.CharField(max_length=100)),
                ('apellidos_trabajador', models.CharField(max_length=100)),
                ('direccion_trabajador', models.CharField(max_length=225)),
                ('fecha_ingreso_trabajador', models.DateTimeField(auto_now_add=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='O', max_length=1)),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cargo')),
            ],
        ),
    ]
