# Generated by Django 5.2.7 on 2025-10-11 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_trabajador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajador',
            old_name='sexo',
            new_name='sexo_trabajador',
        ),
        migrations.CreateModel(
            name='Carga_familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_carga_familiar', models.CharField(max_length=12)),
                ('nombre_carga_familiar', models.CharField(max_length=100)),
                ('parentesco_carga_familiar', models.CharField(max_length=100)),
                ('sexo_carga_familiar', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='O', max_length=1)),
                ('id_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto_emergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto_emergencia', models.CharField(max_length=100)),
                ('parentesco_contacto_emergencia', models.CharField(max_length=50)),
                ('id_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trabajador')),
            ],
        ),
    ]
