# Generated by Django 5.2.7 on 2025-11-17 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_sexo_trabajador_sexo_trabajador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto_emergencia_telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_contacto_emergencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trabajador')),
                ('id_telefono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.telefono')),
            ],
        ),
        migrations.CreateModel(
            name='Marcado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_marcado', models.DateTimeField(auto_now_add=True)),
                ('tipo_marcado', models.CharField(choices=[('E', 'Entrada'), ('S', 'Salida'), ('P', 'Pausa')], max_length=1)),
                ('origen_marcado', models.CharField(choices=[('B', 'Biometrico'), ('M', 'Manual'), ('A', 'App')], max_length=1)),
                ('id_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador_telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_telefono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.telefono')),
                ('id_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trabajador')),
            ],
        ),
    ]
